<img src=https://github.com/numpy/numpy/raw/main/branding/logo/primary/numpylogo.svg width=250 alt="NumPy Logo"></img>
# Numpy


## Overview
NumPy is the fundamental package for scientific computing with Python. It contains among other things:

- a powerful N-dimensional array object
- sophisticated (broadcasting) functions
- useful linear algebra, Fourier transform, and random number capabilities

The NumPy array object is the common interface for working with typed arrays of data across a wide-variety of scientific Python packages. NumPy also features a C-API, which enables interfacing existing Fortran/C/C++ libraries with Python and NumPy. 

The Numpy module is imported with:

In [241]:
import numpy

In [240]:
import numpy as np

This is because Numpy is so often used that it is shorter to type ``np`` than ``numpy``.

## Creating Numpy arrays

The easiest way to create an array is from a Python list, using the ``array`` function:

In [242]:
a = np.array([10, 20.1, 30, 40])

In [ ]:
b = list()
for n in range(5):
    b.append(n)
c = np.array(b)
c

Numpy arrays have several attributes that give useful information about the array:

In [243]:
a.ndim  # number of dimensions
a.shape  # shape of the array
a.dtype  # numerical type

dtype('float64')

### Generation
NumPy also provides helper functions for generating arrays of data to save you typing for regularly spaced data. Don't forget your Python indexing rules!

* `arange(start, stop, step)` creates a range of values in the interval `[start,stop)` with `step` spacing.
* `linspace(start, stop, num)` creates a range of `num` evenly spaced values over the range `[start,stop]`.

In [245]:
d =np.arange(stop=10, start=5, step=1) 
# if start is not given, it will be 0!
# if step is not given, it will be 1!

In [247]:
np.arange(30
)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [248]:
# We can use floats
b = np.arange(1.2, 4.41, 0.1)


In [249]:
# LINSPACE
np.linspace(11, 12, 10)

array([11.        , 11.11111111, 11.22222222, 11.33333333, 11.44444444,
       11.55555556, 11.66666667, 11.77777778, 11.88888889, 12.        ])

and a similar function can be used to create logarithmically spaced values between and including limits:

In [ ]:
np.logspace(1., 4., 7)

Finally, the ``zeros`` and ``ones`` functions can be used to create arrays intially set to ``0`` and ``1`` respectively:

In [250]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [251]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [258]:
# accessing and slicing
b[0]
b[::-2] # Slices [start:end:step]

array([4.4, 4.2, 4. , 3.8, 3.6, 3.4, 3.2, 3. , 2.8, 2.6, 2.4, 2.2, 2. ,
       1.8, 1.6, 1.4, 1.2])

Summarizing:  
- np.array([X, X, X, X])
- np.arange(start, finish, step)
- np.linspace(start, finish-included, number of elements)
- np.zeros([dim, dim]) 1D: np.zeros(X)
- np.ones([dim, dim])
- np.empty([dim, dim])

In [259]:
a.shape

(4,)

In [260]:
b.shape

(33,)

In [265]:
np.vstack([a, a]).shape

(2, 4)

In [266]:
np.hstack([a, b]).shape

(37,)

In [263]:
np.stack([a, a]).shape

(2, 4)

In [267]:
d = np.vstack([a, a])
d.shape

(2, 4)

In [268]:
np.vstack([d, d]).shape

(4, 4)

In [269]:
np.hstack([d, d]).shape

(2, 8)

In [270]:
np.stack([d, d]).shape

(2, 2, 4)

In [271]:
np.dstack([d, d]).shape

(2, 4, 2)

### Exercise

Create an array which contains the value 2 repeated 10 times

In [275]:
a = 1 + np.ones(10)
a

array([2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])

In [277]:
a = np.linspace(2, 2, 10)
a

array([2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])

In [278]:
np.repeat([2], 10)

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

Create an array which contains values from 1 until 90 every one and then the values 95, 99, 99.9, 99.99.

In [283]:
vl = np.arange(0, 91)
vl
vl2 = np.hstack([vl, [95, 99, 99.9, 99.99]])
vl2

array([ 0.  ,  1.  ,  2.  ,  3.  ,  4.  ,  5.  ,  6.  ,  7.  ,  8.  ,
        9.  , 10.  , 11.  , 12.  , 13.  , 14.  , 15.  , 16.  , 17.  ,
       18.  , 19.  , 20.  , 21.  , 22.  , 23.  , 24.  , 25.  , 26.  ,
       27.  , 28.  , 29.  , 30.  , 31.  , 32.  , 33.  , 34.  , 35.  ,
       36.  , 37.  , 38.  , 39.  , 40.  , 41.  , 42.  , 43.  , 44.  ,
       45.  , 46.  , 47.  , 48.  , 49.  , 50.  , 51.  , 52.  , 53.  ,
       54.  , 55.  , 56.  , 57.  , 58.  , 59.  , 60.  , 61.  , 62.  ,
       63.  , 64.  , 65.  , 66.  , 67.  , 68.  , 69.  , 70.  , 71.  ,
       72.  , 73.  , 74.  , 75.  , 76.  , 77.  , 78.  , 79.  , 80.  ,
       81.  , 82.  , 83.  , 84.  , 85.  , 86.  , 87.  , 88.  , 89.  ,
       90.  , 95.  , 99.  , 99.9 , 99.99])

## Numerical operations with arrays

Numpy arrays can be combined numerically using the standard ``+-*/**`` operators:

<div class="admonition alert alert-warning">
    <p class="admonition-title" style="font-weight:bold">Warning</p>
    These arrays must be the same shape!
</div>

In [284]:
x1 = np.array([1,2,3])
y1 = np.array([4,5,6])

In [285]:
y1

array([4, 5, 6])

In [286]:
2 * y1

array([ 8, 10, 12])

In [287]:
(x1 + 2) * y1

array([12, 20, 30])

In [288]:
x1 ** y1

array([  1,  32, 729])

Note that this differs from lists:

In [289]:
x = [1,2,3]
y = [4,5,6, 'hola']

In [290]:
3 * y

[4, 5, 6, 'hola', 4, 5, 6, 'hola', 4, 5, 6, 'hola']

In [291]:
2 * y

[4, 5, 6, 'hola', 4, 5, 6, 'hola']

In [292]:
x + 2 * y

[1, 2, 3, 4, 5, 6, 'hola', 4, 5, 6, 'hola']

### Constants

NumPy provides us access to some useful constants as well - remember you should never be typing these in manually! Other libraries such as SciPy and MetPy have their own set of constants that are more domain specific.

In [293]:
np.pi

3.141592653589793

In [294]:
np.e

2.718281828459045

In [295]:
1 + np.pi

4.141592653589793

### Array math functions

NumPy also has math functions that can operate on arrays. Similar to the math operations, these greatly simplify and speed up these operations. Let's start with calculating $\sin(t)$!

In [296]:
t = np.array([4, 6, 8])
sin_t = np.sin(t)
sin_t

array([-0.7568025 , -0.2794155 ,  0.98935825])

and clean it up a bit by `round`ing to three decimal places.

In [297]:
np.round(sin_t, 3)

array([-0.757, -0.279,  0.989])

In [298]:
cos_t = np.cos(t)
cos_t

array([-0.65364362,  0.96017029, -0.14550003])

<div class="admonition alert alert-info">
    <p class="admonition-title" style="font-weight:bold">Info</p>
    Check out NumPy's list of mathematical functions <a href=https://numpy.org/doc/stable/reference/routines.math.html>here</a>!
</div>

In [ ]:
degrees = np.rad2deg(t)
degrees

We are similarly provided algorithms for operations including integration, bulk summing, and cumulative summing.

In [ ]:
sine_integral = np.trapz(sin_t, t)
np.round(sine_integral, 3)

In [299]:
cos_sum = np.sum(cos_t)
cos_sum

0.1610266319781406

In [300]:
cos_csum = np.cumsum(cos_t)
print(cos_csum)

[-0.65364362  0.30652667  0.16102663]


## Multi-dimensional arrays

In [301]:
y = np.ones([3,2,3])  # ones takes the shape of the array, not the values

In [302]:
y.shape

(3, 2, 3)

In [ ]:
y

Multi-dimensional arrays can be sliced differently along different dimensions:

In [304]:
y[::3, 1:4, :].shape

(1, 1, 3)

## Using axes to slice arrays

Here we introduce an important concept when working with NumPy: the axis. This indicates the particular dimension along which a function should operate (provided the function does something taking multiple values and converts to a single value). 

Let's look at a concrete example with `sum`:

In [305]:
a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

This calculates the total of all values in the array.

In [307]:
np.sum(a)

66

<div class="admonition alert alert-info">
    <p class="title" style="font-weight:bold">Info</p>
    Some of NumPy's functions can be accessed as `ndarray` methods!
</div>

In [ ]:
a.sum()

Now, with a reminder about how our array is shaped,

In [309]:
a.shape

(3, 4)

we can specify `axis` to get _just_ the sum across each of our rows.

In [308]:
np.sum(a, axis=0)

array([12, 15, 18, 21])

Or do the same and take the sum across columns:

In [310]:
np.sum(a, axis=1)

array([ 6, 22, 38])

After putting together some data and introducing some more advanced calculations, let's demonstrate a multi-layered example: calculating temperature advection. If you're not familiar with this (don't worry!), we'll be looking to calculate

\begin{equation*}
\text{advection} = -\vec{v} \cdot \nabla T
\end{equation*}

and to do so we'll start with some random $T$ and $\vec{v}$ values,

In [311]:
temp = np.random.randn(100, 50)
u = np.random.randn(100, 50)
v = np.random.randn(100, 50)

We can calculate the `np.gradient` of our new $T(100x50)$ field as two separate component gradients,

In [312]:
gradient_x, gradient_y = np.gradient(temp)

In [313]:
gradient_x

array([[ 0.90364794, -0.04906123,  0.3068934 , ...,  0.3801925 ,
         1.21721008, -1.84570729],
       [ 0.94495128,  0.17233744,  0.23561591, ..., -0.08647292,
         1.28353356,  0.08918848],
       [ 0.75046518,  0.44463073, -0.81505663, ...,  0.47981328,
        -1.03992647,  0.37329773],
       ...,
       [ 0.54622739,  0.60521453, -0.49058107, ..., -0.72679564,
        -0.5198598 , -0.37515282],
       [-0.34668031, -0.48500809, -0.12997533, ...,  0.60700189,
        -0.35612474,  1.45161158],
       [-0.05572733, -1.00272431, -0.18475133, ...,  1.97533892,
        -0.42595421,  1.91341936]])

In order to calculate $-\vec{v} \cdot \nabla T$, we will use `np.dstack` to turn our two separate component gradient fields into one multidimensional field containing $x$ and $y$ gradients at each of our $100x50$ points,

In [314]:
grad_vectors = np.dstack([gradient_x, gradient_y])
print(grad_vectors.shape)

(100, 50, 2)


and then do the same for our separate $u$ and $v$ wind components,

In [315]:
wind_vectors = np.dstack([u, v])
print(wind_vectors.shape)


(100, 50, 2)


Finally, we can calculate the dot product of these two multidimensional fields of wind and temperature gradient components by hand as an element-wise multiplication, `*`, and then a `sum` of our separate components at each point (i.e., along the last `axis`),

In [316]:
advection = (wind_vectors * -grad_vectors).sum(axis=-1)
print(advection.shape)

(100, 50)


## Masking

The index notation ``[...]`` is not limited to single element indexing, or multiple element slicing, but one can also pass a discrete list/array of indices:

In [317]:
x = np.array([1,6,4,7])

In [320]:
x[[True, False, True, False]]

array([1, 4])

In [321]:
x[x<5]

array([1, 4])

which is returning a new array composed of elements 1, 2, 4, etc from the original array.

Alternatively, one can also pass a boolean array of ``True/False`` values, called a **mask**, indicating which items to keep:

In [322]:
y = np.array([3, 4, 5])

In [326]:
mask = np.array([True, False, False, True])

In [327]:
x[mask]

array([1, 7])

Now this doesn't look very useful because it is very verbose, but now consider that carrying out a comparison with the array will return such a boolean array:

In [ ]:
x

In [328]:
mask = x > 3.4

It is therefore possible to extract subsets from an array using the following simple notation:

In [329]:
x[x > 3.4]

array([6, 4, 7])

In [330]:
x[mask]

array([6, 4, 7])

In [331]:
x[~mask]

array([1])

Conditions can be combined:

### Conditional formating

For Loops --> and, or

For masking ---> & (and), | (or)

In [ ]:
x

In [332]:
x[(x > 3.4) & (x < 5.5)]

array([4])

Of course, the boolean **mask** can be derived from a different array to ``x`` as long as it is the right size:

In [339]:
x = np.linspace(-1., 1., 14)
y = np.array([1,6.,4,7,9.,3,1,5,6,7,3,4,4,3])

In [340]:
y

array([1., 6., 4., 7., 9., 3., 1., 5., 6., 7., 3., 4., 4., 3.])

In [335]:
x.shape

(14,)

In [336]:
y2 = y + 3
y2

array([ 4.,  9.,  7., 10., 12.,  6.,  4.,  8.,  9., 10.,  6.,  7.,  7.,
        6.])

In [343]:
mask = y2 >= 9
yy = y[mask]
yy

array([6., 7., 9., 6., 7.])

In [344]:
y[(x > -0.5) | (x < 0.4)]

array([1., 6., 4., 7., 9., 3., 1., 5., 6., 7., 3., 4., 4., 3.])

Since the mask itself is an array, it can be stored in a variable and used as a mask for different arrays:

In [345]:
keep = (x > -0.5) & (x < 0.4)
x = x[keep]
y_new = y[keep]

In [346]:
x = np.array([3, 8, 9, 12, 2])
x

array([ 3,  8,  9, 12,  2])

In [347]:
x[(x>5) & (x<10)]

array([8, 9])

In [350]:
for xi in x:
    if (xi>5) and (xi<10):
        print(xi)

8
9


In [ ]:
x_new

In [ ]:
y_new

we can use this conditional indexing to assign new values to certain positions within our array, somewhat like a masking operation.

In [ ]:
y

In [ ]:
mask = y>5
mask

In [ ]:
y[mask] = 999

In [ ]:
y

In [ ]:
y1 = y[mask]
y1

In [ ]:
mm = y > 3

In [ ]:
mm

In [ ]:
y[mm] = np.NaN # np.nan, np.NAN

In [ ]:
y

In [ ]:
y[y > 5] = 3

### NaN values

In arrays, some of the values are sometimes NaN - meaning *Not a Number*. If you multiply a NaN value by another value, you get NaN, and if there are any NaN values in a summation, the total result will be NaN. One way to get around this is to use ``np.nansum`` instead of ``np.sum`` in order to find the sum:

In [ ]:
x = np.array([1,2,3,np.NaN])
x

In [ ]:
np.NAN # np.nan | np.NaN | np.NAN

In [ ]:
np.nansum(x)

In [ ]:
np.nansum(x)

In [ ]:
np.nanmax(x)

You can also use ``np.isnan`` to tell you where values are NaN. For example, ``array[~np.isnan(array)]`` will return all the values that are not NaN (because ~ means 'not'):

In [ ]:
np.isnan(x)

In [ ]:
x[np.isnan(x)]

In [ ]:
x[~np.isnan(x)]

## Exercise

The [data/SIMAR_gaps.txt](data/SIMAR_gaps.txt) data file gives the wave climate data in the Mediterranean Sea.

Read in the file using ``np.loadtxt``. The data contains bad values, which you can identify by looking at the minimum and maximum values of the array. Use masking to get rid of the bad values.

In [379]:
from pathlib import Path
dir_data = Path('data')
data = np.loadtxt(dir_data / 'SIMAR_gaps.txt', skiprows=1)
#np.genfromtxt()
var = data[:, 4]

In [372]:
np.max(var)
# var.max()

3.5

In [380]:
np.min(var)

-99.9

In [376]:
var[var < 0] = np.NaN

In [383]:
var[var == np.min(var)] = np.NaN

In [387]:
np.nanmin(var)

0.5

## Using broadcasting to implicitly loop over data

### What is broadcasting?
Broadcasting is a useful NumPy tool that allows us to perform operations between arrays with different shapes, provided that they are compatible with each other in certain ways. To start, we can create an array below and add 5 to it:

In [390]:
a = np.array([10, 20, 30, 40])
a + 5  # works with a number

array([15, 25, 35, 45])

In [392]:
b = np.array([5])
b

array([5])

In [393]:
a +b

array([15, 25, 35, 45])

This takes the single element in `b` and adds it to each of the elements in `a`. This won't work for just any `b`, though; for instance, the following won't work:

In [394]:
b = np.array([5, 6, 7])
a + b

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

It does work if `a` and `b` are the same shape:

In [395]:
b = np.array([5, 5, 10, 10])
a + b

array([15, 25, 40, 50])

What if what we really want is pairwise addition of a and b? Without broadcasting, we could accomplish this by looping:

In [396]:
b = np.array([1, 2, 3, 4, 5])

In [397]:
a

array([10, 20, 30, 40])

In [398]:
b

array([1, 2, 3, 4, 5])

In [399]:
result = np.empty((5, 4), dtype=np.int32)
for row, valb in enumerate(b):
    for col, vala in enumerate(a):
        result[row, col] = vala + valb
result

array([[11, 21, 31, 41],
       [12, 22, 32, 42],
       [13, 23, 33, 43],
       [14, 24, 34, 44],
       [15, 25, 35, 45]], dtype=int32)

### Giving NumPy room for broadcasting
We can also do this using broadcasting, which is where NumPy implicitly repeats the array without using additional memory. With broadcasting, NumPy takes care of repeating for you, provided dimensions are "compatible". This works as follows:
1. Check the number of dimensions of the arrays. If they are different, *prepend* dimensions of size one until the arrays are the same dimension shape.
2. Check if each of the dimensions are compatible. This works as follows:
  - Each dimension is checked.
  - If one of the arrays has a size of 1 in the checked dimension, or both arrays have the same size in the checked dimension, the check passes.
  - If all dimension checks pass, the dimensions are compatible.

For example, consider the following arrays:

In [400]:
a.shape

(4,)

In [ ]:
b.shape

Right now, these arrays both have the same number of dimensions.  They both have only one dimension, but that dimension is incompatible.  We can solve this by appending a dimension using `np.newaxis` when indexing, like this:

In [401]:
bb = b[:, np.newaxis]
bb.shape

(5, 1)

In [402]:
bb

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [403]:
a + bb

array([[11, 21, 31, 41],
       [12, 22, 32, 42],
       [13, 23, 33, 43],
       [14, 24, 34, 44],
       [15, 25, 35, 45]])

In [404]:
(a + bb).shape

(5, 4)

We can also make the code more succinct by performing the newaxis and addition operations in a single line, like this:

In [ ]:
a + b[:, np.newaxis]

### Extending to higher dimensions
The same broadcasting ability and rules also apply for arrays of higher dimensions. Consider the following arrays `x`, `y`, and `z`, which are all different dimensions. We can use newaxis and broadcasting to perform $x^2 + y^2 + z^2$:

In [405]:
x = np.array([1, 2])
y = np.array([3, 4, 5])
z = np.array([6, 7, 8, 9])

First, we extend the `x` array using newaxis, and then square it.  Then, we square `y`, and broadcast it onto the extended `x` array:

In [406]:
d_2d = x[:, np.newaxis] ** 2 + y**2

In [407]:
d_2d.shape

(2, 3)

Finally, we further extend this new 2-D array to a 3-D array using newaxis, square the `z` array, and then broadcast `z` onto the newly extended array:

In [408]:
d_3d = d_2d[..., np.newaxis] + z**2

In [409]:
d_3d.shape

(2, 3, 4)

As described above, we can also perform these operations in a single line of code, like this:

In [ ]:
h = x[:, np.newaxis, np.newaxis] ** 2 + y[np.newaxis, :, np.newaxis] ** 2 + z**2

Given the 3-D temperature field and 1-D pressure coordinates below, let's calculate $T * exp(P / 1000)$. We will need to use broadcasting to make the arrays compatible.  The following code demonstrates how to use newaxis and broadcasting to perform this calculation:

In [ ]:
pressure = np.array([1000, 850, 500, 300])
temps = np.linspace(20, 30, 24).reshape(4, 3, 2)


## Vectorize calculations to avoid explicit loops

When working with arrays of data, loops over the individual array elements is a fact of life. However, for improved runtime performance, it is important to avoid performing these loops in Python as much as possible, and let NumPy handle the looping for you. Avoiding these loops frequently, but not always, results in shorter and clearer code as well.

### Look ahead/behind

One common pattern for vectorizing is in converting loops that work over the current point, in addition to the previous point and/or the next point. This comes up when doing finite-difference calculations, e.g., approximating derivatives:

\begin{equation*}
f'(x) = f_{i+1} - f_{i}
\end{equation*}

In [410]:
a = np.linspace(0, 20, 6)
a

array([ 0.,  4.,  8., 12., 16., 20.])

In [412]:
d = a[1:] - a[:-1]
d

array([4., 4., 4., 4., 4.])

We can calculate the forward difference for this array using a manual loop, like this:

In [413]:
d = np.zeros(a.size - 1)
for i in range(len(a) - 1):
    d[i] = a[i + 1] - a[i]
d

array([4., 4., 4., 4., 4.])

It would be nice to express this calculation without a loop, if possible. To see how to go about this, let's consider the values that are involved in calculating `d[i]`; in other words, the values `a[i+1]` and `a[i]`. The values over the loop iterations are:

|  i  | a[i+1] | a[i] |
| --- |  ----  | ---- |
|  0  |    4   |   0  |
|  1  |    8   |   4  |
|  2  |   12   |   8  |
|  3  |   16   |  12  |
|  4  |   20   |  16  |

We can then express the series of values for `a[i+1]` as follows:

In [ ]:
a[1:]

We can also express the series of values for `a[i]` as follows:

In [ ]:
a[:-1]

This means that we can express the forward difference using the following statement:

In [ ]:
a[1:] - a[:-1]

#### 2nd Derivative
    
A finite-difference estimate of the 2nd derivative is given by the following equation (ignoring $\Delta x$):

\begin{equation*}
f''(x) = 2
f_i - f_{i+1} - f_{i-1}
\end{equation*}

Let's write some vectorized code to calculate this finite difference for `a`, using slices.  Analyze the code below, and compare the result to the values you would expect to see from the 2nd derivative of `a`.

In [415]:
a = np.linspace(0, 20, 16)
a

array([ 0.        ,  1.33333333,  2.66666667,  4.        ,  5.33333333,
        6.66666667,  8.        ,  9.33333333, 10.66666667, 12.        ,
       13.33333333, 14.66666667, 16.        , 17.33333333, 18.66666667,
       20.        ])

In [416]:
d2 = 2*a[1:-1] - a[2:] - a[:-2]
d2

array([ 0.00000000e+00, -2.22044605e-16,  4.44089210e-16,  0.00000000e+00,
       -8.88178420e-16,  1.77635684e-15, -1.77635684e-15,  0.00000000e+00,
        1.77635684e-15, -1.77635684e-15,  0.00000000e+00,  1.77635684e-15,
        0.00000000e+00, -3.55271368e-15])

d2 = 2*a[1:-1] - a[2:] - a[:-2]
d2
